authentication/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from authentication import views
from authentication.forms import UserLoginForm, CustomPasswordResetForm, CustomPasswordResetConfirmForm
from signup.views import add_intern_records
from dashboard.views import announcement_list
from dashboard.views import intern_announcement_list

urlpatterns = [
    # login view from auth_views with custom login template
    path('', auth_views.LoginView.as_view(template_name='authentication/login.html',
                                          redirect_authenticated_user=True, form_class=UserLoginForm), name='root'),

    path('login/', auth_views.LoginView.as_view(template_name='authentication/login.html',
                                                # True means that if user is already logged in, it will redirect to homepage
                                                redirect_authenticated_user=True, form_class = UserLoginForm), name='login',),

    # logout view from auth_view
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    # path for register view
    path('register/', views.register, name='register'),

    #path for activate view
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),

    #path to reset password
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='authentication/password_reset.html',
        form_class=CustomPasswordResetForm,  # Specify your custom form here
    ), name='password_reset'),

    #path to password_reset_done
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='authentication/password_reset_done.html'), name='password_reset_done'),

    #path to password_reset_confirm
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='authentication/password_reset_confirm.html',
        form_class=CustomPasswordResetConfirmForm  # Use the custom form
    ), name='password_reset_confirm'),

    #path to password reset complete
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='authentication/password_reset_complete.html'), name='password_reset_complete'),


    # path for homepage where successfull login will redirect
    path('homepage/', views.homepage, name='homepage'),

    path('add_intern_records/', add_intern_records, name='add_intern_records'),

    path('announcement_list/', announcement_list, name='announcement_list'),

    path('intern_announcement_list/', intern_announcement_list, name='intern_announcement_list'),


]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('', include('signup.urls')),
    path('', include('dashboard.urls')),
    path('', include('internlist.urls')),
    path('', include('documents.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

signup/models.py
# Create your models here.
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now
from django.utils.safestring import mark_safe

from documents.models import Folder


# Create your models here.
class Intern_Records(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    folder = models.ForeignKey(Folder, on_delete=models.SET_NULL, blank=True, null=True)
    student_id = models.CharField(max_length=200, verbose_name='Student ID', null=True)
    middle_name = models.CharField(max_length=200, verbose_name='Middle Name', null=True)
    suffix = models.CharField(max_length=200, verbose_name='suffix', null=True)
    present_address = models.CharField(max_length=200, verbose_name='Present Address', null=True)
    academic_year = models.CharField(max_length=200, verbose_name='Academic Year', null=True)
    SEMESTER_CHOICES = [
        ('1st Semester', '1st Semester'),
        ('2nd Semester', '2nd Semester'),
    ]
    semester = models.CharField(max_length=20, choices=SEMESTER_CHOICES, null=True)

    course = models.CharField(
        max_length=10,
        verbose_name='Course',
        choices=(
            ('BSIT', 'BSIT'),
            ('BSIS', 'BSIS'),
            ('BSCS', 'BSCS'),
            ('BSA', 'BSA'),
            ('BSAIS', 'BSAIS'),
            ('BPA', 'BPA'),
            ('BSE', 'BSE'),
        ),
        null=True
    )

    # Method to get OJT hours based on the selected course
    def get_ojt_hours(self):
        COURSE_OJT_HOURS = {
            'BSIT': 366,
            'BSIS': 366,
            'BSCS': 182,
            'BSA': 300,
            'BSAIS': 400,
            'BPA': 300,
            'BSE': 300,
        }
        return COURSE_OJT_HOURS.get(self.course, 0)


    def get_remaining_ojt_hours(self):
        COURSE_OJT_HOURS = {
            'BSIT': 366,
            'BSIS': 366,
            'BSCS': 182,
            'BSA': 300,
            'BSAIS': 400,
            'BPA': 300,
            'BSE': 300,
        }
        total_required_hours = COURSE_OJT_HOURS.get(self.course, 0)
        remaining_hours = total_required_hours - self.weekly_hours
        return remaining_hours

    weekly_hours = models.PositiveIntegerField(default=0, verbose_name='Weekly Hours')
    year_level = models.CharField(max_length=200, verbose_name='Year Level', null=True)
    block = models.CharField(max_length=200, verbose_name='Block', null=True)

    company_name = models.CharField(max_length=200, verbose_name='Company', null=True)
    address = models.CharField(max_length=200, verbose_name='Address', null=True)

    contact_person = models.CharField(max_length=200, verbose_name='Contact Person', null=True)
    contact_number = models.CharField(max_length=200, verbose_name='Contact Number', null=True)

    profile_image = models.ImageField(upload_to='profile_images/', default='profile_images/SSUProfile.png')
    pub_date = models.DateTimeField(default=now)

    # Intern Status
    STATUS_CHOICES = [
        ('Not Placed', 'Not Placed'),
        ('On OJT', 'On OJT'),
        ('Late OJT', 'Late OJT'),
        ('On Leave', 'On Leave'),
        ('Suspended', 'Suspended'),
        ('Resigned', 'Resigned'),
        ('Extended', 'Extended'),
        ('Terminated', 'Terminated'),
        ('Completed', 'Completed'),
    ]

    @property
    def status_badge(self):
        # Define a dictionary that maps status choices to corresponding background colors
        status_colors = {
            'Not Placed': '#4d5059',
            'On OJT': '#00e738',  # Change color for 'On OJT' to green
            'Late OJT': '#ff8000',  # Change color for 'Terminated' to orange
            'On Leave': '#edbc62', # Change color for 'On Leave' to apricot
            'Suspended': '#1e1f22',  # Change color for 'Resigned' to black
            'Resigned': '#0000ff',  # Change color for 'Suspended' to blue
            'Extended': '#f2c115',  # Change color for 'Extended' to yellow
            'Terminated': '#ff0000',  # Change color for 'Late OJT' to red
            'Completed': '#00ffff',  # Change color for 'Completed' to cyan
        }

        # Get the CSS class based on the status choice
        background_color = status_colors.get(self.status, '')

        # Return the badge HTML

        return mark_safe(
            f'<span class="badge" style="background-color: {background_color}; color: white;">{self.status}</span>')

    status = models.CharField(max_length=20, choices=STATUS_CHOICES, null=True)

    form_filled_out = models.BooleanField(default=False)

    def __str__(self):
        return str(self.user.username)

authentication/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, SetPasswordForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordResetForm
from django import forms


# uncomment this if you want to change the class/design of the login form
class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']



    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Username',
            'required': 'True'
        })
        self.fields['password'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Password',
            'required': 'True'
        })


# Customizing Registration Form from UserCreationForm


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']

    # uncomment this if you want to change the class/design of the registration form inputs
    def __init__(self, *args, **kwargs):
        super(UserRegistrationForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'First Name',
            'required': 'True'
        })
        self.fields['last_name'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Last Name',
            'required': 'True'
        })
        self.fields['username'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Username',
            'required': 'True'
        })
        self.fields['email'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Email',
            'required': 'True'
        })


        self.fields['password1'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Password',
            'required': 'True'
        })
        self.fields['password2'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Retype Password',
            'required': 'True'
        })

class CustomPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(
        label="Email",
        widget=forms.EmailInput(attrs={
            'class': 'form-control',
            'placeholder': 'Enter your email'}),
    )

    def clean_email(self):
        email = self.cleaned_data.get('email')
        # Add custom validation logic here if needed
        return email



class CustomPasswordResetConfirmForm(SetPasswordForm):
    new_password1 = forms.CharField(
        label="New Password",
        widget=forms.PasswordInput(attrs={
            'class': 'form-control'}),
    )

    new_password2 = forms.CharField(
        label="Confirm New Password",
        widget=forms.PasswordInput(attrs={
            'class': 'form-control'}),
    )

authentication/views.py
# import this to require login
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

# import this for sending email to user
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import LoginView
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode

from authentication.forms import UserRegistrationForm
from dashboard.models import Announcement
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.
from signup.models import Intern_Records


@login_required(login_url='login')
def homepage(request):
    if request.user.is_superuser:

        return redirect('announcement_list')

    # Check if the user has already filled out the form
    try:
        intern_record = Intern_Records.objects.get(user=request.user)
        if intern_record.form_filled_out:
            announcements = Announcement.objects.all().order_by('-pub_date')
            context = {
                'announcements': announcements,
            }

            return redirect('intern_announcement_list')
    except Intern_Records.DoesNotExist:
        pass
    return redirect('add_intern_records')



def register(request):
    form = UserRegistrationForm()


    if request.method == "POST":
        form = UserRegistrationForm(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()

            # email user with activation link
            current_site = get_current_site(request)
            mail_subject = "Activate your account."

            # the message will render what is written in authentication/email_activation/activate_email_message.html
            message = render_to_string('authentication/email_activation/activate_email_message.html', {
                    'user': form.cleaned_data['username'],
                    #'intern': intern_form.cleaned_data['student_id'],
                    'domain': current_site.domain,
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                    'token':  default_token_generator.make_token(user),
                })
            to_email = form.cleaned_data['email']
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.send()
            messages.success(request, 'Account created successfully. Please check your email to activate your account.')
            return redirect('login')
        else:
            for field, errors in form.errors.items():
                for error in errors:
                    if field in ['password1', 'password2']:
                        # Display password validation errors
                        messages.error(request, error)
                    else:
                        # Display other form field errors
                        messages.error(request, f"{field}: {error}")

            #messages.error(request, 'Account creation failed. Please try again.')


    return render(request, 'authentication/register.html',{
        'form': form,
    })

# to activate user from email
def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        return render(request, 'authentication/email_activation/activation_successful.html')
    else:
        return render(request, 'authentication/email_activation/activation_unsuccessful.html')

templates/authentication/intern_create.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
    <title>Set Up Account Page|SorSU-BC Monitoring System</title>

    <!-- General CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/modules/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/modules/fontawesome/css/all.min.css' %}">

    <!-- CSS Libraries -->
    <link rel="stylesheet" href="{% static 'assets/modules/jquery-selectric/selectric.css' %}">
    <link rel="website icon" type="png" href="{% static 'assets/img/SSUlogo.png' %}"

    <!-- Template CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/preloader.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/components.css' %}">
    <!-- Start GA -->

    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-94034622-3"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }

        gtag('js', new Date());

        gtag('config', 'UA-94034622-3');
    </script>

</head>
<body style="background-color: #e7e7e7;
        background-image: url('{% static 'assets/img/SorSu_cover.jpg' %}');
        background-size: cover;
        background-repeat: no-repeat;
        background-attachment: fixed; /* Optional: Fixed background image */
        /* Additional styling properties like background-position, background-color, etc. */
        ">

<div class="wrapper" id="loader">
    <div class="box-wrap">
        <div class="box one"></div>
        <div class="box two"></div>
        <div class="box three"></div>
        <div class="box four"></div>
        <div class="box five"></div>
        <div class="box six"></div>
    </div>
</div>

<div class="container mt-5">
    <div class="row">
        <div class="col-12 col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-8 offset-lg-2 col-xl-8 offset-xl-2">
            <div class="login-brand">
                <img src="{% static 'assets/img/SSUlogo.png' %}" alt="logo" width="100"
                     class="shadow-light rounded-circle">
            </div>

            <div class="card card-primary" style="background-color: rgba(255, 255, 255, 0.9);">
                <div class="card-header"><h4>Set Up Account</h4></div>

                {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}

                <div class="card-body">
                    <form method="POST" action="{% url 'add_intern_records' %}" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row">
                            <div class="form-group col-6">
                                <label>First Name</label> <br>
                                {{ user.first_name }}
                            </div>

                            <div class="form-group col-6">
                                <label for="middle_name">Middle Initial</label>
                                {% if form.middle_name.value != 'n/a' %}
                                    {{ form.middle_name }}
                                {% endif %}
                            </div>

                            <div class="form-group col-6">
                                <label>Last Name</label><br>
                                {{ user.last_name }}
                            </div>

                            <div class="form-group col-6">
                                <label for="suffix">Suffix</label>
                                {% if form.suffix.value != 'n/a' %}
                                    {{ form.suffix }}
                                {% endif %}
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="present_address">Present Address</label>
                            {{ form.present_address }}
                        </div>
                        <div class="row">
                            <div class="form-group col-6">
                                <label for="academic_year">Academic Year</label>
                                {{ form.academic_year }}
                            </div>

                            <div class="form-group col-6">
                                <label for="{{ form.semester.id_for_label }}">Semester</label>
                                {{ form.semester }}
                            </div>
                        </div>
                        <div class="row">

                            <div class="form-group col-4">
                                <label for="{{ form.course.id_for_label }}">Course</label>
                                {{ form.course }}
                            </div>

                            <div class="form-group col-4">
                                <label for="year_level">Year Level</label>
                                {{ form.year_level }}
                            </div>

                            <div class="form-group col-4">
                                <label for="block">block</label>
                                {{ form.block }}
                            </div>

                            <div class="form-group col-6">
                                <label for="ojt_hours">OJT Hours:</label>
                                <span id="ojt_hours_value">{{ max_hours }} hrs</span>
                            </div>
                        </div>

                        <div class="row">
                            <div class="form-group col-6">
                                <label>Email</label><br>
                                {{ user.email }}
                            </div>

                            <div class="form-group col-6">
                                <label for="student_id">Student Number</label>
                                {{ form.student_id }}
                            </div>
                        </div>

                        <div class="form-group">
                            <label>Username</label><br>
                            {{ user.username }}
                        </div>

                        <div class="row">
                            <div class="form-group col-6">
                                <label for="company_name">Company Name</label>
                                {% if form.company_name.value != 'n/a' %}
                                    {{ form.company_name }}
                                {% endif %}
                            </div>

                            <div class="form-group col-6">
                                <label for="address">Company Address</label>
                                {% if form.address.value != 'n/a' %}
                                    {{ form.address }}
                                {% endif %}
                            </div>

                            <div class="form-group col-6">
                                <label for="contact_person">Contact Person</label>
                                {{ form.contact_person }}
                            </div>

                            <div class="form-group col-6">
                                <label for="contact_number">Contact Address</label>
                                {{ form.contact_number }}
                            </div>

                            <div class="form-group col-6">
                                <label for="profile_image">Profile Image</label>
                                {{ form.profile_image }}
                            </div>

                            <div class="form-group col-6">
                                <label for="status">Internship Status</label>
                                {{ form.status }}
                            </div>
                        </div>

                </div>

                <div class="form-divider">
                    <div class="form-group text-center"> <!-- Add the 'text-center' class here -->
                        <button type="submit" value="submit" class="btn btn-primary btn-lg">
                            Register
                        </button>
                        <p>To Logout: <a href="{% url 'logout' %}">Click here</a></p>
                    </div>
                </div>

                </form>
            </div>
        </div>
    </div>
</div>
</div>

<script>
    window.addEventListener('load', function () {
        const loader = document.getElementById('loader');
        setTimeout(function () {
            loader.style.opacity = '0';
            setTimeout(function () {
                loader.style.display = 'none';
            }, 1000); // Hide the loader 1 second after fading out
        }, 2000); // Start fading out after 2 seconds
    });

</script>

<!-- General JS Scripts -->
<script src="{% static 'assets/modules/jquery.min.js' %}"></script>
<script src="{% static 'assets/modules/popper.js' %}"></script>
<script src="{% static 'assets/modules/tooltip.js' %}"></script>
<script src="{% static 'assets/modules/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/modules/nicescroll/jquery.nicescroll.min.js' %}"></script>
<script src="{% static 'assets/modules/moment.min.js' %}"></script>
<script src="{% static 'assets/js/stisla.js' %}"></script>

<!-- JS Libraries -->
<script src="{% static 'assets/modules/jquery-pwstrength/jquery.pwstrength.min.js' %}"></script>
<script src="{% static 'assets/modules/jquery-selectric/jquery.selectric.min.js' %}"></script>

<!-- Page Specific JS File -->
<script src="{% static 'assets/js/page/auth-register.js' %}"></script>

<!-- Template JS File -->
<script src="{% static 'assets/js/scripts.js' %}"></script>
<script src="{% static 'assets/js/custom.js' %}"></script>

<script>
    $(document).ready(function () {
        $('#id_course').on('change', function () {
            var selectedCourse = $(this).val();
            var ojtHours = {
                'BSIT': 366,
                'BSIS': 366,
                'BSCS': 182,
                'BSA': 300,
                'BSAIS': 400,
                'BPA': 300,
                'BSE': 300,
            };

            var ojtHoursValue = ojtHours[selectedCourse] || 0;
            $('#ojt_hours_value').text(ojtHoursValue + ' hrs');
        });
    });
</script>

</body>
</html>

templates/authentication/password_reset.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
    <title>Password Reset Panel|SorSU-BC Monitoring System</title>
    <link rel="website icon" type="png" href="{% static 'assets/img/SSUlogo.png' %}">
    <!-- General CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/modules/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/modules/fontawesome/css/all.min.css"' %}>

  <!-- CSS Libraries -->
  <link rel=" stylesheet
    " href="{% static 'assets/modules/bootstrap-social/bootstrap-social.css' %}">

    <!-- Template CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/preloader.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/components.css' %}">
    <!-- Start GA -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-94034622-3"></script>

    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }

        gtag('js', new Date());

        gtag('config', 'UA-94034622-3');
    </script>
    <!-- /END GA --></head>

<body style="background-color: #e7e7e7;
        background-image: url('{% static 'assets/img/SorSu_cover.jpg' %}');
        background-size: cover;
        background-repeat: no-repeat;
        background-attachment: fixed; /* Optional: Fixed background image */
        /* Additional styling properties like background-position, background-color, etc. */
        ">

<div class="wrapper" id="loader">
    <div class="box-wrap">
        <div class="box one"></div>
        <div class="box two"></div>
        <div class="box three"></div>
        <div class="box four"></div>
        <div class="box five"></div>
        <div class="box six"></div>
    </div>
</div>

<div id="app">
    <section class="section">
        <div class="container mt-5">
            <div class="row">
                <div class="col-12 col-sm-8 offset-sm-2 col-md-6 offset-md-3 col-lg-6 offset-lg-3 col-xl-4 offset-xl-4">
                    <div class="login-brand">
                        <img src="{% static 'assets/img/SSUlogo.png' %}" alt="logo" width="100"
                             class="shadow-light rounded-circle">
                    </div>

                    <div class="card card-primary" style="background-color: rgba(255, 255, 255, 0.8);">
                        <div class="card-header"><h4>Password Reset</h4></div>

                        <div class="card-body">
                            <form method="POST" action="#" class="needs-validation" novalidate="">
                                {% csrf_token %}
                                {{ form }}
                                <br>
                                <div class="form-group">
                                    <button type="submit" value="submit" class="btn btn-primary btn-lg btn-block">
                                        Send Email
                                    </button>
                                </div>

                            </form>


                            <div class="mt-5 text-muted text-center">
                                <p>To login: <a href="{% url 'login' %}">Click Here</a></p>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
</div>
<script>
    window.addEventListener('load', function () {
        const loader = document.getElementById('loader');
        setTimeout(function () {
            loader.style.opacity = '0';
            setTimeout(function () {
                loader.style.display = 'none';
            }, 1000); // Hide the loader 1 second after fading out
        }, 2000); // Start fading out after 2 seconds
    });

</script>

<!-- General JS Scripts -->
<script src="{% static 'assets/modules/jquery.min.js' %}"></script>
<script src="{% static 'assets/modules/popper.js' %}"></script>
<script src="{% static 'assets/modules/tooltip.js' %}"></script>
<script src="{% static 'assets/modules/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/modules/nicescroll/jquery.nicescroll.min.js' %}"></script>
<script src="{% static 'assets/modules/moment.min.js' %}"></script>
<script src="{% static 'assets/js/stisla.js' %}"></script>

<!-- JS Libraies -->

<!-- Page Specific JS File -->

<!-- Template JS File -->
<script src="{% static 'assets/js/scripts.js' %}"></script>
<script src="{% static 'assets/js/custom.js' %}"></script>
</body>
</html>